/* eslint-disable @next/next/no-img-element -- curated public-source road-trip imagery is rendered with visible provenance. */
import type { SignatureDrive } from "./product-domain.ts";
import Link from "next/link";
import ProductNav, { ProductBrand } from "./ProductNav.tsx";

const hours = (minutes: number) => minutes ? `${Math.floor(minutes / 60)}h${minutes % 60 ? ` ${minutes % 60}m` : ""}` : "Keys down";

export default function DriveProductPage({ drive }: { drive: SignatureDrive }) {
  const canTransact = drive.transactionStatus === "transaction-ready-demo";
  return <main className="drive-product">
    <ProductNav inverse />
    <section className="drive-product-hero"><img src={drive.heroMedia.imageUrl} alt={drive.heroMedia.alt} /><div /><article><p>{drive.region} · Signature Drive</p><h1>{drive.name}</h1><h2>{drive.tagline}</h2><div><span>{drive.recommendedDays} days</span><span>{drive.distanceKm} km · demo-content</span><span>{drive.drivingDifficulty.replaceAll("-", " ")}</span></div></article><a href={drive.heroMedia.sourceUrl} target="_blank" rel="noreferrer">Photo: {drive.heroMedia.author} · {drive.heroMedia.licenseNote}</a></section>
    <section className="drive-intro"><div><p className="v2-overline">Why this road</p><h2>{drive.summary}</h2><p>{drive.story}</p><div className="drive-themes">{drive.themes.map((theme) => <span key={theme}>{theme}</span>)}</div></div><aside><small>Route at a glance</small><ol>{drive.stops.map((stop, index) => <li key={stop}><span>{String(index + 1).padStart(2, "0")}</span>{stop}</li>)}</ol><p><strong>Best seasons</strong>{drive.bestSeasons.join(" · ")}</p></aside></section>
    <section className="drive-capability"><div><span>{canTransact ? "✓" : "○"}</span><p><small>{canTransact ? "Transaction-ready demo" : "Content-ready journey"}</small><strong>{canTransact ? "This route can enter the validated Yunnan planner." : "Explore and compare this known journey without fabricated inventory."}</strong></p></div><p>{canTransact ? "Route, vehicle and optional stay choices use the existing deterministic demo catalog. No live supplier or payment is connected." : "The editorial road trip is ready for fit and trade-off comparisons. Executable route, vehicle, hotel and booking steps stay unavailable until a local graph and inventory boundary exist."}</p></section>
    {drive.dailyJourney.length ? <section className="drive-days"><header><p className="v2-overline">The daily journey</p><h2>Ten days where the road is part of the story.</h2><p>Times, distances, stays and experiences are structured demo-content. Verify current road and access conditions before travel.</p></header><div>{drive.dailyJourney.map((day) => <article key={day.dayNumber}><span>Day {String(day.dayNumber).padStart(2, "0")}</span><div><small>{day.destination} · {day.distanceKm ? `${day.distanceKm} km · ${hours(day.estimatedDrivingMinutes)}` : "No through-drive"}</small><h3>{day.title}</h3><p>{day.roadStory}</p><dl><div><dt>Road rhythm</dt><dd>Leave {day.bestDepartureTime} · {day.scenery.join(" · ")}</dd></div><div><dt>Stop for</dt><dd>{day.stops.join(" · ")} · {day.food.join(" · ")}</dd></div><div><dt>Parking</dt><dd>{day.parking}</dd></div><div><dt>Stay</dt><dd>{day.suggestedStay}</dd></div></dl></div></article>)}</div></section> : <section className="drive-editorial-outline"><p className="v2-overline">Journey outline</p><h2>{drive.stops.join(" → ")}</h2><p>{drive.roadCharacteristics.join(" · ")}. The Advisor can compare this known route shape and traveler fit, but a day-by-day executable itinerary is not yet available.</p></section>}
    <section className="drive-practical"><header><p className="v2-overline">Driving character</p><h2>What the road asks of you.</h2></header><div><article><small>Road profile</small><h3>{drive.suitability.roadSurface.replaceAll("-", " ")}</h3><p>{drive.roadCharacteristics.join(". ")}.</p></article><article><small>Altitude</small><h3>{drive.suitability.altitudeExposure}</h3><p>Longest standard drive: {hours(drive.suitability.longestDrivingMinutes)}. Service confidence: {drive.suitability.serviceConfidence.replaceAll("-", " ")}.</p></article><article><small>Parking</small><h3>{drive.suitability.parkingDifficulty}</h3><p>{drive.parkingNotes[0]}</p></article><article><small>Vehicle direction</small><h3>{drive.recommendedVehicleTypes.join(" · ")}</h3><p>Recommendation context is route-specific; all vehicle availability remains demo-mock.</p></article></div></section>
    {drive.alternativeVersions.length > 0 && <section className="drive-variants"><header><p className="v2-overline">Make it yours</p><h2>One road, three different rhythms.</h2></header><div>{drive.alternativeVersions.map((variant) => <article key={variant.id}><small>{variant.days} days</small><h3>{variant.name}</h3><p>{variant.description}</p><span>{variant.travelerFit.join(" · ")}</span><Link href={`/plan?drive=${drive.slug}&variant=${variant.id}`}>Customize this version →</Link></article>)}</div></section>}
    <section className="drive-final-cta"><p>{canTransact ? "Ready to shape the Yunnan drive around you?" : "Want to compare this road before booking exists?"}</p><h2>{canTransact ? "Keep the route. Change the rhythm." : "Understand the fit, without fake availability."}</h2><Link href={`/plan?drive=${drive.slug}`}>{canTransact ? "Customize with AI" : "Compare with the Travel Advisor"} <span>✦</span></Link></section>
    <footer className="product-footer"><ProductBrand /><p>Curated road trips · source-bound guidance · deterministic Trip authority</p><Link href="/road-trips">All Signature Drives</Link></footer>
  </main>;
}
